<script lang="ts">
	import type { PageData } from './$types';
	import { page } from '$app/stores';
	import { heroTyping } from '$lib/actions/typing';
	import { assetUrl, formatDate } from '$lib/utils';
	import { buildLqipStyle, buildResponsiveAttrs } from '$lib/responsive-image';
	import { buildWebSiteSchema, buildPersonSchema, serializeJsonLd } from '$lib/seo';

	let { data }: { data: PageData } = $props();
	const bundle        = $derived(data.bundle);
	const config        = $derived(bundle?.config);
	const gallery       = $derived(data.gallery);
	const imageManifest = $derived(data.imageManifest ?? null);
	const homePageConfig = $derived(data.homePageConfig ?? null);

	// Hero fields — YAML takes precedence over config.json
	const hero         = $derived(homePageConfig?.hero);
	const heroTitle    = $derived(hero?.title ?? config?.hero_title ?? config?.title ?? '');
	const heroSubtitle = $derived(hero?.subtitle ?? config?.hero_subtitle ?? config?.description ?? '');

	// SEO
	const seoTitle       = $derived(homePageConfig?.seo?.title ?? config?.hero_title ?? config?.title ?? '');
	const seoDescription = $derived(homePageConfig?.seo?.description ?? config?.description ?? config?.hero_subtitle ?? '');
	const seoKeywords    = $derived(homePageConfig?.seo?.keywords ?? []);

	const siteUrl = $derived(
		String(config?.site_url || config?.url || $page.url.origin).replace(/\/+$/, '')
	);
	const webSiteJsonLd = $derived(config ? buildWebSiteSchema(config, siteUrl) : null);
	const personJsonLd  = $derived(config?.author ? buildPersonSchema(config, siteUrl) : null);

	// Sections from YAML, or fall back to legacy hardcoded order
	const enabledSections = $derived(
		homePageConfig?.sections?.filter((s) => s.enabled !== false) ?? []
	);
	const useLegacyLayout = $derived(enabledSections.length === 0);

	// Legacy layout derived values
	// Auto-generated by build-metadata.js from actual gallery images — not configurable
	const galleryCover = '/content/assets/images/gallery-cover.webp';
	const postThumbSizes  = '(max-width: 480px) 100px, (max-width: 640px) 120px, 180px';

	function blogPostHref(slug: string): string { return `/blog/post/${slug}/`; }
	function portfolioHref(slug: string): string { return `/portfolio/${slug}/`; }

	// Resolve posts/portfolio for a given section config
	function getSectionPosts(section: typeof enabledSections[number]) {
		const all = bundle?.posts ?? [];
		if (!section.categories?.length) return all.slice(0, section.limit ?? all.length);
		const cats = section.categories;
		const filtered = all.filter(
			(p) => cats.includes(p.category ?? '') || p.tags?.some((t) => cats.includes(t))
		);
		return filtered.slice(0, section.limit ?? filtered.length);
	}

	function getSectionPortfolio(section: typeof enabledSections[number]) {
		const all = bundle?.portfolio ?? [];
		const filtered = section.featuredOnly ? all.filter((p) => p.featured) : all;
		return filtered.slice(0, section.limit ?? filtered.length);
	}

	function getSectionThoughts(section: typeof enabledSections[number]) {
		return (bundle?.thoughts ?? []).slice(0, section.limit ?? 2);
	}
</script>

<svelte:head>
	<title>{seoTitle}</title>
	<meta name="description" content={seoDescription} />
	{#if seoKeywords.length}
		<meta name="keywords" content={seoKeywords.join(', ')} />
	{/if}
	{#if webSiteJsonLd}
		{@html `<script type="application/ld+json">${serializeJsonLd(webSiteJsonLd)}</script>`}
	{/if}
	{#if personJsonLd}
		{@html `<script type="application/ld+json">${serializeJsonLd(personJsonLd)}</script>`}
	{/if}
</svelte:head>

<!-- ── Hero ─────────────────────────────────────────── -->
<section class="home-hero" id="profile-hero">
	<div class="home-hero-aurora" aria-hidden="true"></div>
	<div class="home-hero-content">
		{#if hero?.eyebrow}
			<p class="home-hero-eyebrow">{hero.eyebrow}</p>
		{/if}
		<h1 class="home-hero-title" aria-label={heroTitle}>
			<span class="accent-gradient" use:heroTyping={heroTitle}></span>
		</h1>
		{#if heroSubtitle}
			<p class="home-hero-subtitle">{heroSubtitle}</p>
		{/if}
		{#if hero?.description}
			<p class="home-hero-description">{hero.description}</p>
		{/if}
		{#if hero?.actions?.length}
			<div class="home-hero-actions">
				{#each hero.actions as action}
					<a href={action.href} class="home-btn home-btn-{action.variant ?? 'secondary'}">
						{action.label}
					</a>
				{/each}
			</div>
		{/if}
	</div>
	<div class="hero-waves" aria-hidden="true">
		<svg class="hero-wave hero-wave-back" viewBox="0 0 1440 80" preserveAspectRatio="none"><path d="M0,45 C100,20 200,55 360,30 C480,12 560,50 720,35 C850,22 1000,55 1140,28 C1280,8 1380,42 1440,38 L1440,80 L0,80 Z"/></svg>
		<svg class="hero-wave hero-wave-front" viewBox="0 0 1440 80" preserveAspectRatio="none"><path d="M0,38 C80,52 180,15 320,42 C430,60 540,18 700,40 C820,55 960,12 1100,45 C1220,62 1340,22 1440,35 L1440,80 L0,80 Z"/></svg>
	</div>
</section>

<!-- ── YAML-driven sections ──────────────────────────── -->
{#if !useLegacyLayout}
	{#each enabledSections as section (section.id ?? section.type)}

		<!-- blog posts (filtered by categories) -->
		{#if section.type === 'blog'}
			{@const posts = getSectionPosts(section)}
			{#if posts.length}
				<div class="home-section">
					<div class="home-section-header">
						<h2>{section.title ?? 'Recent Posts'}</h2>
						<a href="/blog" aria-label="All blog posts">All blog posts →</a>
					</div>
					{#if section.description}
						<p class="home-section-desc">{section.description}</p>
					{/if}
					<div class="post-list">
						{#each posts as post, i}
							<a class="post-card{post.cover ? ' has-thumb' : ''}" href={blogPostHref(post.slug)}>
								{#if post.cover}
									{@const lqip = buildLqipStyle(post.cover, imageManifest)}
									<div class="post-card-thumb is-loading" class:lqip-shown={!!lqip} style={lqip}>
										<img {...buildResponsiveAttrs(post.cover, imageManifest, { sizes: postThumbSizes, eager: i === 0, maxWidth: 640 })} alt="" aria-hidden="true" />
									</div>
								{/if}
								<div class="post-card-body">
									<div class="post-card-title">{post.title}</div>
									{#if post.summary}<div class="post-card-summary">{post.summary}</div>{/if}
									<div class="post-card-meta">
										<time datetime={post.date}>{formatDate(post.date)}</time>
										{#if post.category}<span class="post-card-category">{post.category}</span>{/if}
										{#each (post.tags ?? []).slice(0, 2) as tag}
											<span class="tag" style="padding:2px 8px;font-size:11px">{tag}</span>
										{/each}
									</div>
								</div>
							</a>
						{/each}
					</div>
				</div>
			{/if}

		<!-- portfolio / projects -->
		{:else if section.type === 'projects'}
			{@const items = getSectionPortfolio(section)}
			{#if items.length}
				<div class="home-section">
					<div class="home-section-header">
						<h2>{section.title ?? 'Projects'}</h2>
						<a href="/portfolio" aria-label="All portfolio projects">All portfolio projects →</a>
					</div>
					{#if section.description}
						<p class="home-section-desc">{section.description}</p>
					{/if}
					<div class="portfolio-grid">
						{#each items as item}
							<div class="portfolio-card">
								<div class="portfolio-card-title">
									<a href={portfolioHref(item.slug)}>{item.title}</a>
								</div>
								{#if item.summary}<div class="portfolio-card-summary">{item.summary}</div>{/if}
								{#if item.tags?.length}
									<div class="portfolio-card-tags">
										{#each item.tags.slice(0, 3) as tag}
											<span class="tag" style="padding:3px 10px;font-size:11px">{tag}</span>
										{/each}
									</div>
								{/if}
								{#if item.github || item.demo}
									<div class="portfolio-card-links">
										{#if item.github}
											<a href={item.github} target="_blank" rel="noopener" class="btn-github">
												<svg width="14" height="14" viewBox="0 0 16 16" fill="currentColor"><path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27s1.36.09 2 .27c1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.01 8.01 0 0016 8c0-4.42-3.58-8-8-8z"/></svg>
												GitHub
											</a>
										{/if}
										{#if item.demo}
											<a href={item.demo} target="_blank" rel="noopener" class="btn-demo">Demo</a>
										{/if}
									</div>
								{/if}
							</div>
						{/each}
					</div>
				</div>
			{/if}

		<!-- static info/link cards from YAML items -->
		{:else if section.type === 'cards'}
			{#if section.items?.length}
				<div class="home-section">
					<div class="home-section-header">
						<h2>{section.title ?? 'Topics'}</h2>
					</div>
					{#if section.description}
						<p class="home-section-desc">{section.description}</p>
					{/if}
					<div class="home-info-cards">
						{#each section.items as item}
							{#if item.href}
								<a href={item.href} class="home-info-card home-info-card-link">
									{#if item.icon}<span class="home-info-card-icon">{item.icon}</span>{/if}
									<div class="home-info-card-title">{item.title ?? item.label ?? ''}</div>
									{#if item.description}<p class="home-info-card-desc">{item.description}</p>{/if}
									{#if item.tags?.length}
										<div class="home-info-card-tags">
											{#each item.tags as tag}
												<span class="tag" style="padding:2px 8px;font-size:11px">{tag}</span>
											{/each}
										</div>
									{/if}
									<span class="home-info-card-arrow">→</span>
								</a>
							{:else}
								<div class="home-info-card">
									{#if item.icon}<span class="home-info-card-icon">{item.icon}</span>{/if}
									<div class="home-info-card-title">{item.title ?? item.label ?? ''}</div>
									{#if item.description}<p class="home-info-card-desc">{item.description}</p>{/if}
									{#if item.tags?.length}
										<div class="home-info-card-tags">
											{#each item.tags as tag}
												<span class="tag" style="padding:2px 8px;font-size:11px">{tag}</span>
											{/each}
										</div>
									{/if}
								</div>
							{/if}
						{/each}
					</div>
				</div>
			{/if}

		<!-- link list -->
		{:else if section.type === 'links'}
			{#if section.items?.length}
				<div class="home-section">
					<div class="home-section-header">
						<h2>{section.title ?? 'Links'}</h2>
					</div>
					{#if section.description}
						<p class="home-section-desc">{section.description}</p>
					{/if}
					<div class="home-links-list">
						{#each section.items as item}
							<a href={item.href ?? '/'} class="home-link-item">
								<div class="home-link-item-label">{item.label ?? item.title ?? ''}</div>
								{#if item.description}<p class="home-link-item-desc">{item.description}</p>{/if}
								<span class="home-link-item-arrow">→</span>
							</a>
						{/each}
					</div>
				</div>
			{/if}

		<!-- thoughts -->
		{:else if section.type === 'thoughts'}
			{@const thoughts = getSectionThoughts(section)}
			{#if thoughts.length}
				<div class="home-section">
					<div class="home-section-header">
						<h2>{section.title ?? 'Thoughts'}</h2>
						<a href="/thoughts" aria-label="All thoughts">All thoughts →</a>
					</div>
					{#if section.description}
						<p class="home-section-desc">{section.description}</p>
					{/if}
					<div class="thoughts-list">
						{#each thoughts as thought}
							<div class="thought-card">
								<p class="thought-body">{thought.body ?? thought.title}</p>
								<div class="thought-meta">
									{#if thought.title}<span class="thought-title">{thought.title}</span><span>·</span>{/if}
									<span>{formatDate(thought.date)}</span>
								</div>
							</div>
						{/each}
					</div>
				</div>
			{/if}

		<!-- gallery widget -->
		{:else if section.type === 'gallery'}
			{#if gallery && gallery.length > 0}
				{@const stackSources = galleryCover ? [galleryCover, galleryCover, galleryCover] : gallery.slice(0, 3).map((g) => g.image ?? g.images?.[0]?.src ?? '')}
				{#if stackSources.length}
					<div class="home-section">
						{#if section.title}
							<div class="home-section-header">
								<h2>{section.title}</h2>
								<a href="/gallery" aria-label="All gallery items">All gallery items →</a>
							</div>
						{/if}
						{#if section.description}
							<p class="home-section-desc">{section.description}</p>
						{/if}
						<div class="gallery-window">
							<a href="/gallery" class="gallery-window-link" aria-label="View gallery">
								<div class="gallery-window-chrome">
									<div class="gallery-window-dots">
										<span class="dot red"></span>
										<span class="dot yellow"></span>
										<span class="dot green"></span>
									</div>
									<div class="gallery-window-title">Gallery</div>
								</div>
								<div class="gallery-window-body">
									<div class="gallery-stack">
										{#each [0, 1, 2] as idx}
											{@const src = stackSources[Math.min(idx, stackSources.length - 1)]}
											{@const lqip = buildLqipStyle(src, imageManifest)}
											<div class="gallery-stack-card layer-{idx + 1} is-loading" class:lqip-shown={!!lqip} style={lqip}>
												<img {...buildResponsiveAttrs(src, imageManifest, { sizes: '(max-width: 900px) 72vw, 560px', maxWidth: 960 })} alt="Gallery preview {idx + 1}" />
											</div>
										{/each}
									</div>
								</div>
							</a>
						</div>
					</div>
				{/if}
			{/if}

		<!-- free text / prose -->
		{:else if section.type === 'text'}
			{#if section.body}
				<div class="home-section">
					{#if section.title}
						<div class="home-section-header">
							<h2>{section.title}</h2>
						</div>
					{/if}
					<p class="home-text-body">{section.body}</p>
				</div>
			{/if}
		{/if}

	{/each}

<!-- ── Legacy fallback layout (no homepage.yaml sections) ── -->
{:else}

	{#if bundle?.posts?.length}
		<div class="home-section">
			<div class="home-section-header">
				<h2>Recent Posts</h2>
				<a href="/blog" aria-label="All blog posts">All blog posts →</a>
			</div>
			<div class="post-list">
				{#each bundle.posts.slice(0, 3) as post, i}
					<a class="post-card{post.cover ? ' has-thumb' : ''}" href={blogPostHref(post.slug)}>
						{#if post.cover}
							{@const lqip = buildLqipStyle(post.cover, imageManifest)}
							<div class="post-card-thumb is-loading" class:lqip-shown={!!lqip} style={lqip}>
								<img {...buildResponsiveAttrs(post.cover, imageManifest, { sizes: postThumbSizes, eager: i === 0, maxWidth: 640 })} alt="" aria-hidden="true" />
							</div>
						{/if}
						<div class="post-card-body">
							<div class="post-card-title">{post.title}</div>
							{#if post.summary}<div class="post-card-summary">{post.summary}</div>{/if}
							<div class="post-card-meta">
								<time datetime={post.date}>{formatDate(post.date)}</time>
								{#if post.category}<span class="post-card-category">{post.category}</span>{/if}
								{#each (post.tags ?? []).slice(0, 2) as tag}
									<span class="tag" style="padding:2px 8px;font-size:11px">{tag}</span>
								{/each}
							</div>
						</div>
					</a>
				{/each}
			</div>
		</div>
	{/if}

	{#if bundle?.portfolio?.length}
		<div class="home-section">
			<div class="home-section-header">
				<h2>Projects</h2>
				<a href="/portfolio" aria-label="All portfolio projects">All portfolio projects →</a>
			</div>
			<div class="portfolio-grid">
				{#each bundle.portfolio.slice(0, 4) as item}
					<div class="portfolio-card">
						<div class="portfolio-card-title"><a href={portfolioHref(item.slug)}>{item.title}</a></div>
						{#if item.summary}<div class="portfolio-card-summary">{item.summary}</div>{/if}
						{#if item.tags?.length}
							<div class="portfolio-card-tags">
								{#each item.tags.slice(0, 3) as tag}
									<span class="tag" style="padding:2px 8px;font-size:11px">{tag}</span>
								{/each}
							</div>
						{/if}
						{#if item.github || item.demo}
							<div class="portfolio-card-links">
								{#if item.github}<a href={item.github} target="_blank" rel="noopener" class="btn-github">GitHub</a>{/if}
								{#if item.demo}<a href={item.demo} target="_blank" rel="noopener" class="btn-demo">Demo</a>{/if}
							</div>
						{/if}
					</div>
				{/each}
			</div>
		</div>
	{/if}

	{#if gallery && gallery.length > 0}
		{@const stackSources = galleryCover ? [galleryCover, galleryCover, galleryCover] : gallery.slice(0, 3).map((g) => g.image ?? g.images?.[0]?.src ?? '')}
		{#if stackSources.length}
			<div class="home-section">
				<div class="gallery-window">
					<a href="/gallery" class="gallery-window-link" aria-label="View gallery">
						<div class="gallery-window-chrome">
							<div class="gallery-window-dots">
								<span class="dot red"></span><span class="dot yellow"></span><span class="dot green"></span>
							</div>
							<div class="gallery-window-title">Gallery</div>
						</div>
						<div class="gallery-window-body">
							<div class="gallery-stack">
								{#each [0, 1, 2] as idx}
									{@const src = stackSources[Math.min(idx, stackSources.length - 1)]}
									{@const lqip = buildLqipStyle(src, imageManifest)}
									<div class="gallery-stack-card layer-{idx + 1} is-loading" class:lqip-shown={!!lqip} style={lqip}>
										<img {...buildResponsiveAttrs(src, imageManifest, { sizes: '(max-width: 900px) 72vw, 560px', maxWidth: 960 })} alt="Gallery preview {idx + 1}" />
									</div>
								{/each}
							</div>
						</div>
					</a>
				</div>
			</div>
		{/if}
	{/if}

	{#if bundle?.thoughts?.length}
		<div class="home-section">
			<div class="home-section-header">
				<h2>Thoughts</h2>
				<a href="/thoughts" aria-label="All thoughts">All thoughts →</a>
			</div>
			<div class="thoughts-list">
				{#each bundle.thoughts.slice(0, 2) as thought}
					<div class="thought-card">
						<p class="thought-body">{thought.body ?? thought.title}</p>
						<div class="thought-meta">
							{#if thought.title}<span class="thought-title">{thought.title}</span><span>·</span>{/if}
							<span>{formatDate(thought.date)}</span>
						</div>
					</div>
				{/each}
			</div>
		</div>
	{/if}

{/if}
